services:
  postgres:
    restart: always
    image: postgres:16.2-alpine
    ports:
      - 0.0.0.0:${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
